include $(APPDIR)/Make.defs
PROGNAME = hello_oled
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE = $(CONFIG_EXAMPLES_HELLO_OLED)
MAINSRC = hello_oled_main.c
include $(APPDIR)/Application.mk
